### ISSUE TITLE
Verification and retry in tce-load download.

### ISSUE THREAD

**Issue by Magicloud** [tinycorelinux/Core-scripts#1]
I tried to load packages at boot time over Internet from a customized repo and got a few issues.
1.  The repo server does not reply HTTP 404 if a .dep was not found. Hence tce-load takes it as a .dep and tries to download a bunch of non-sense-s.
2.  Since it is Internet, some long time download may get interrupted. And tce-load just skip it. This makes attending-less booting impossible.

**Comment by clbr** [comment]
1 seems like an issue with your server. No server should return garbage data for a nonexistent file.
For 2, it was not intended for packages to be downloaded every boot; if local storage is not desired, how about a NFS server?

**Comment by Magicloud** [comment]
Thanks for the reply.
1.  The service is hosted on cloud service actually, it returns webpage claiming file not existing. We cannot change the behavior yet.
2.  We have a kind of installation mechanism to persist the packages on local storage. But the persisting itself is done in Tinycorelinux, which means we have to load some packages at booting (from network).

**Comment by clbr** [comment]
1 is still a niche case, given most servers are "real" servers,
returning correct errors. It would be better for that modification to
be local to your use.

For 2, it is not really possible, as busybox wget does not distinguish
errors. If the network is down, DNS fails, etc, it would be a waste of
the users' time to retry; only if a download was interrupted should a
retry be tried. And that condition cannot be detected currently.

So, I'd recommend for you to change to a different downloader program,
perhaps one that can handle interrupted downloads inside it
automatically. That would also be a local modification for you then,
as we try to keep to busybox programs to keep the base small.

**Comment by Magicloud** [comment]
OK. Thank you for the advises. Let me see how it can be done.
