### ISSUE TITLE
Repo does not have licensing information

### ISSUE THREAD

**Issue by bdantas** [tinycorelinux/Core-scripts#13]
I know from this that the TCL scripts are licensed under GPL:
http://forum.tinycorelinux.net/index.php/topic,23390.msg146558.html?PHPSESSID=0e4d8800a42a041c0020de305cfdf537#msg146558

Nevertheless, it would be nice if the licensing were made explicit. Maybe a "LICENSE" file could be added to the root of the git repository?

**Comment by clbr** [comment]
Added, thanks.
