### ISSUE TITLE
Create tags for released versions

### ISSUE THREAD

**Issue by herrfrei** [tinycorelinux/Core-scripts#22]
It would by good to have tags for each published version of TCL. The current master revision should be 12.0, shouldn't it?

**Comment by juanitotc** [comment]
I tried to add a tag - it seems to have been done, but I don't see it anywhere..

**Comment by herrfrei** [comment]
Juanito, did you push it to the remote (github) repo? You may take a look at https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository if you need some tips.

**Comment by juanitotc** [comment]
I pushed it and git tag shows a tag - maybe Curaga can figure things out..

**Comment by clbr** [comment]
Did you do "git push --tags"?

**Comment by juanitotc** [comment]
Aaah - just done that now...

**Comment by herrfrei** [comment]
Fine, thanks! I'll close the issue now.
