### ISSUE TITLE
Changes in busybox 1.34

### ISSUE THREAD

**Issue by paul-1** [tinycorelinux/Core-scripts#23]
I try to keep up with upcoming changes in busybox, so new releases don't get out of hand.  One change is

awk: disallow break/continue outside of loops
https://git.busybox.net/busybox/commit/?h=1_34_stable&id=d3480dd58211d9d8c06ec7ef00089262603003ff

This breaks at least https://github.com/tinycorelinux/Core-scripts/blob/master/usr/bin/select, perhaps others I've not found yet.
https://github.com/tinycorelinux/Core-scripts/blob/3076f1ae536b895abbb0107f743b17ca24f31877/usr/bin/select#L25
https://github.com/tinycorelinux/Core-scripts/blob/3076f1ae536b895abbb0107f743b17ca24f31877/usr/bin/select#L29

I'm not the best awk coder, but would using return instead of break be correct for these two lines?

**Comment by clbr** [comment]
No, return is similarly undefined in the context. exit should be
correct.

**Comment by paul-1** [comment]
Sounds good, I'll look around and see if I can find other cases that need changed, and then submit a PR.
