### ISSUE TITLE
unable to reach anyone about TCL forum

### ISSUE THREAD

**Issue by ssybesma** [tinycorelinux/Core-scripts#50]
The captcha is broken and I cannot register.

**Comment by clbr** [comment]
We know.

**Comment by ssybesma** [comment]
Thanks.

Not sure of the future intent but I did have questions as I wanted to 
use it on my Intel Compute Sticks.

Would be so perfect.

Steve

On 2023-03-09 23:48, clbr wrote:

> We know.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/tinycorelinux/Core-scripts/issues/50#issuecomment-1463350945
[2]

**Comment by clbr** [comment]
It's up to the forum admin when it'll be fixed, and he seems busy. We do have IRC channels where folks may be able to help with your questions.

**Comment by ssybesma** [comment]
Thank you clbr.

I haven't used IRC in decades and prefer forum postings.

Guess I'll have to wait.

I can offer a $25 donation for someone if they can help with the  initrd 
error I got trying to boot dCorePlus-focal64.iso

Steve

On 2023-03-10 02:35, clbr wrote:

> It's up to the forum admin when it'll be fixed, and he seems busy. We 
> do have IRC channels where folks may be able to help with your 
> questions.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/tinycorelinux/Core-scripts/issues/50#issuecomment-1463526861
[2]

**Comment by ColdForest** [comment]
FWIW, I've tried IRC at both Freenode and Libera with no response (whenever I've checked the channels are completely quiescent). Along with others I'm also stuck here waiting for the forum registration stuff to get sorted. Was hoping there might be a sideband way to get registered manual (_e.g._, by sending an email to the wiki/forum admin but this doesn't appear to be an option).

**Comment by ssybesma** [comment]
I tried these email addresses (two were guessed based on forum admin's 
names) and they delayed delivery for days and finally failed.

***@***.***

***@***.***

***@***.***

***@***.***

Given CF's comments below, the distro will suffer without fresh new 
people able to participate.

Even searching is not allowed unless you register so it's hard to use 
the forum at all.

Steve

On 2023-03-20 10:03, ColdForest wrote:

> FWIW, I've tried IRC at both Freenode and Libera with no response 
> (whenever I've checked the channels are completely quiescent). Along 
> with others I'm also stuck here waiting for the forum registration 
> stuff to get sorted. Was hoping there might be a sideband way to get 
> registered manual (_e.g._, by sending an email to the wiki/forum admin 
> but this doesn't appear to be an option).
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/tinycorelinux/Core-scripts/issues/50#issuecomment-1476514959
[2]

**Comment by ColdForest** [comment]
I'm finally registered. 

Standby for a post in the forum (in the _Forum/Wiki Hosting_ board) regarding a work around for this registration issue. I had my colleague take a look at this (he'll likely post a hint for a, hopefully simple, solution for this so the administrators can help to get this fully sorted)...

**Comment by ssybesma** [comment]
Thank you CF.

I suspect you found a way to deal with the 2nd non-functional Captcha.

I'll take a look where you suggested.

Steve

On 2023-03-20 15:56, ColdForest wrote:

> I'm finally registered.
> 
> Standby for a post in the forum (in the _Forum/Wiki Hosting_ board) 
> regarding a work around for this registration issue. I had my colleague 
> take a look at this (he'll likely post a hint for a, hopefully simple, 
> solution for this so the administrators can help to get this fully 
> sorted)...
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/tinycorelinux/Core-scripts/issues/50#issuecomment-1476986930
[2]

**Comment by ssybesma** [comment]
If anyone can answer in the meantime, I need to be able to install Tiny 
Core Linux on a UEFI-only system.

It has to be 64-bit. 32-bit won't work.

The x86 Pure 64 didn't boot.

Steve

On 2023-03-20 15:56, ColdForest wrote:

> I'm finally registered.
> 
> Standby for a post in the forum (in the _Forum/Wiki Hosting_ board) 
> regarding a work around for this registration issue. I had my colleague 
> take a look at this (he'll likely post a hint for a, hopefully simple, 
> solution for this so the administrators can help to get this fully 
> sorted)...
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/tinycorelinux/Core-scripts/issues/50#issuecomment-1476986930
[2]

**Comment by ssybesma** [comment]
Please disregard my last. It does boot when I created a bootable USB 
using Ventoy.

On 2023-03-21 01:41, ***@***.*** wrote:

> If anyone can answer in the meantime, I need to be able to install Tiny 
> Core Linux on a UEFI-only system.
> 
> It has to be 64-bit. 32-bit won't work.
> 
> The x86 Pure 64 didn't boot.
> 
> Steve
> 
> On 2023-03-20 15:56, ColdForest wrote:
> 
>> I'm finally registered.
>> 
>> Standby for a post in the forum (in the _Forum/Wiki Hosting_ board) 
>> regarding a work around for this registration issue. I had my 
>> colleague take a look at this (he'll likely post a hint for a, 
>> hopefully simple, solution for this so the administrators can help to 
>> get this fully sorted)...
>> 
>> --
>> Reply to this email directly, view it on GitHub [1], or unsubscribe 
>> [2].
>> You are receiving this because you authored the thread.Message ID: 
>> ***@***.***>


Links:
------
[1] 
https://github.com/tinycorelinux/Core-scripts/issues/50#issuecomment-1476986930
[2]

**Comment by tlaurion** [comment]
Broken for me as well. Two capchas, one not functional showing fixed sliders that should be moving...

**Comment by Mirppc** [comment]
Sorry this is broken.  The official IRC on Libera and the tem there has been disconnected from the forums devs and the rest of the team for more than a decade.  We try our best to help but when it comes to the forums we (the irc team) are not able to help much regarding this issue.  I hope this issue will get resolved by the forum admin.

Mir

**Comment by saper** [comment]
> Broken for me as well. Two capchas, one not functional showing fixed sliders that should be moving...

Remove [the second captcha using DOM inspector](https://forum.tinycorelinux.net/index.php/topic,25947.msg168262.html#msg168262) and it should allow registration.

**Comment by saper** [comment]
Instructions for Firefox:
- Complete first Captcha with pictures
- Accept the agreement
You should see two captchas, the second one has broken controls:
![image](https://user-images.githubusercontent.com/248374/234987037-b9be55c5-046b-45a9-bc2b-13a44e67903f.png)
- Right click on the broken captcha and select "Inspect"
-   In the Inspector window find the node with `<div class="windowbg2">`
-  Right click on the node and select "Delete node"
-  Fill in the form, solve other captchas and press "Register"

**Comment by ssybesma** [comment]
That did work.

Caveat: make sure you delete the correct windowbg2 because there is more 
than one and that the 2nd (broken) captcha is the one that should 
disappear, not the first one.

I failed the first two tries and succeeded on the 3rd.

Steve

On 2023-04-27 14:51, Marcin Cieślak wrote:

> Instructions for Firefox:
> 
> * Complete first Captcha with pictures
> 
> * Accept the agreement
> You should see two captchas, the second one has broken controls:
> [1]     * Right click on the broken captcha and select "Inspect"
> * In the Inspector window find the node with <div class="windowbg2">
> * Right click on the node and select "Delete node"
> * Fill in the form, solve other captchas and press "Register"
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://user-images.githubusercontent.com/248374/234987037-b9be55c5-046b-45a9-bc2b-13a44e67903f.png
[2] 
https://github.com/tinycorelinux/Core-scripts/issues/50#issuecomment-1526433476
[3]

**Comment by CardealRusso** [comment]
i belive this issue can be closed as the forum registration is fixed now?
